package userInterface;

public enum ObserverActions {

	CONSOLE_PANEL_CONTENTS, ENABLE_TEXT_EDITOR, UPDATE_CONTENTS, ENABLE_TEXTEDITORTOOLBAR_BUTTONS, SET_TEXT_CONTENT,
	ENABLE_SAVE_BUTTONS, UPDATE_FILE_EXPLORER_PANEL_BUTTONS, UPDATE_PANEL_CONTENTS, ENABLE_CONSOLE_PANEL,
	ENABLE_READING_LISTENER,ADD_PROJECT_TREE, CLOSE_TAB, SAVED_SINGLE_FILE, UPDATE_PROJECT_TREE_ADD, UPDATE_PROJECT_TREE_REMOVE

}
